/*Abstract and extend method
Create Animal class 
Instance field name, age 
Contractor to set those 2 fields 
Abstract void method called makeNoise 
Abstract method called getInfo
It has param as food 
Return String */


public  abstract class Animals {
public string Name;
public Integer age;

public Animals(){
     this.Name = Name;
     this.age = age;
}

public abstract void makeNoise();
 public abstract string getInfo(string food);
   
}